### ISSUE TITLE
Handle multiple definitions inside single query string

### ISSUE THREAD

**Issue by vilvaathibanpb** [product-ride/hql-tag#1]

**Comment by razi-ed** [comment]
Can I please work on this?

**Comment by vilvaathibanpb** [comment]
@razi-ed  Sure, you can. Let me know if you need any help :)

**Comment by vilvaathibanpb** [comment]
Closing as hql-tag already supports multiple definitions :)

**Comment by razi-ed** [comment]
adding for reference: [ hql tag in action with multiple definitions](https://codesandbox.io/s/hql-tag-with-n-definitions-mie93)
