### ISSUE TITLE
Awesome Hasura

### ISSUE THREAD

**Issue by aaronhayes** [product-ride/hql-tag#13]
This project looks brilliant! 
I would love to see a PR over to add it on [awesome-hasura](https://github.com/aaronhayes/awesome-hasura)

**Comment by vilvaathibanpb** [comment]
Hey @aaronhayes , Thanks for the issue. I have raised a PR - https://github.com/aaronhayes/awesome-hasura/pull/19

**Comment by aaronhayes** [comment]
All merged 👍
