### ISSUE TITLE
Setup CI (circle CI or Github actions)

### ISSUE THREAD

**Issue by vilvaathibanpb** [product-ride/hql-tag#5]

**Comment by idawud** [comment]
I've create a PR on this. Right now it runs only the tests, Should we include an action to publish to npm?

**Comment by vilvaathibanpb** [comment]
Hey @idawud , Thanks for the PR. I had a look at it. Its good. And yea, we could add publish to npm as well. Later we can also add for lint  check as well.

**Comment by idawud** [comment]
@vilvaathibanpb Are we looking at publishing on **new release** or when we **push to master**?

**Comment by vilvaathibanpb** [comment]
We could publish for every push to master. When we have a major release, we will update it manually.

**Comment by idawud** [comment]
you'll have to add the **NPM_TOKEN** to the secrets

**Comment by vilvaathibanpb** [comment]
Thank you for the contribution :) Closing the issue
